### ISSUE TITLE
Make www.ballotapi.com https by default

### ISSUE THREAD

**Issue by diafygi** [open-austin/ballotapi#20]
I have the SSL cert, just need to update apache.

**Comment by dsernst** [comment]
https://www.cloudflare.com/ is also very easy to setup, and offers free https for incoming connections. Still requires your own cert between CloudFlare and your server to encrypt that traffic, but this covers 90% of the problem and is incredibly easy and free to set up.

**Comment by afomi** [comment]
Heroku offers free, easy-to-setup SSL for instances that run a dyno for $7/month.

**Comment by diafygi** [comment]
Done for https://ballotapi.org/
