### ISSUE TITLE
Publish a project roadmap (or similar)

### ISSUE THREAD

**Issue by afomi** [open-austin/ballotapi#23]
As a Contributor
I want to understand the direction, goals, and vision for this project
So that I can more effectively contribute

Given I visit the repo
When I read the README 
And I click on a link
Then I can read more about what the project needs and where it is going

**Comment by afomi** [comment]
I see there's a bit in the existing readme... but I didn't see any code - just docs

Perhaps I'm in the wrong repo? Is the API elsewhere?

**Comment by diafygi** [comment]
Howdy, correct, this project is currently just docs (I wrote the docs and examples first to figure out how the API should work). Next up is the prototype API itself. https://github.com/open-austin/ballotapi#current-status
