### ISSUE TITLE
Make a pretty website

### ISSUE THREAD

**Issue by diafygi** [open-austin/ballotapi#26]
The current website is just a placeholder for the API docs. We need a much prettier website with other pages beyond just the documentation.

## Thoughts on the website
* No huge frameworks or libraries. This is a simple static website, so there's absolutely no reason to make pages bloated. Required watching: [The Website Obesity Crisis](https://www.webdirections.org/blog/the-website-obesity-crisis/) ([slides](https://idlewords.com/talks/website_obesity.htm))
* The current website uses an old version of Bootstrap with the default theme. It's fast, but looks like it was designed by an engineer (because it was). Maybe we can use the [U.S. Web Design framework](https://designsystem.digital.gov/)? Seems appropriate since this is all about U.S. election information. Also, it's a super simple and lightweight framework since it has to serve all citizens and has great accessibility features.
* Docs, examples, and tutorials should be written by humans for humans. They already are, but don't be tempted to switch to generated docs. I'm fine with adding generated schemas, but those should be secondary to making great human-readable docs.

**Comment by jcklpe** [comment]
alternatively, I'm currently helping a couple of other non profit orgs set up and use this wordpress theme, so might be easy to convert over to it. Just a thought. Might make keeping documentation up to date easier. 

https://github.com/SeattleDSA/dsa_wordpress

**Comment by jcklpe** [comment]
Hey check out this project I'm working on @diafygi https://github.com/jcklpe/common-wp

Still has some work to go but should be useful for you guys probably.

**Comment by diafygi** [comment]
Possible hero images?
* https://www.pexels.com/search/america/
* https://www.pexels.com/photo/woman-women-united-states-of-america-flag-92730/

**Comment by diafygi** [comment]
Switched the landing and about-us pages to use the USWDS framework.

**Comment by jcklpe** [comment]
@diafygi sounds like you are not interested in using the CMS solution I proposed? That's cool, I just want to check in, and see if there's anything with it that I could do differently that would make it more useful for your project. 

I know that WP gets a bad rap but I specifically built the theme to be essentially self contained. Having a CMS is heavier than running a static site generator etc, but it's also not always as easy for non-devs to update the content of which is why I suggest it.

**Comment by diafygi** [comment]
@jcklpe Yeah, I think sticking with Jekyll and just a static Github Pages site is best for now. There's really no need for a dynamic backend or CMS at the moment. Until we actually get a demo running, I don't think there will be much in the way of news/blogs/posts/etc. that non-devs would need to be able to post.

**Comment by jcklpe** [comment]
@diafygi  sounds good! :) Looking forward to seeing this project evolve.

**Comment by diafygi** [comment]
Converted the rest of the pages to use USWDS, so I think we're good until the prototype is working.
