### ISSUE TITLE
Design a BallotAPI logo

### ISSUE THREAD

**Issue by diafygi** [open-austin/ballotapi#27]
We need a logo for BallotAPI.

## Thoughts on the logo
* Needs to work in color, grayscale, and monotone. Color for the main website. Grayscale for printed/copied materials (hackathon handouts, etc.). Monotone for screen printing (t-shirts, pens, swag, etc.).
* Needs to have a favicon version for the website tab.
* Needs to have a small version for a "powered by BallotAPI"-style badge below embedded widgets.

**Comment by tracykm** [comment]
made one here https://github.com/open-austin/ballotapi/pull/34

**Comment by diafygi** [comment]
@tracykm Thanks so much! If I merge the pull request, the logo will be public domain. Is that okay with you?

**Comment by diafygi** [comment]
Also, what fonts did you use?

**Comment by tracykm** [comment]
Of course! Public domain is fine. I used Avenir Next.

**Comment by diafygi** [comment]
Merged!
